# levels
# debug = -1
# info = 0
# warn = 1
# error = 2
log_level: -1
log_to_file: true

# test mode - everything works the same way, except all network notifications
# are blocked and nothing is written to the database. Used for testing features, bugs
test_mode: false

mongo:
  # enable migration mode only if you want to convert a sqlite database to a mongo database
  migration_mode: false
  mongo_uri: "mongodb://kramer-mongo:27017"
  mongo_dbname: "usersdb"
  mongo_collname: "users"

# scraper config
scrapers:
  ozbargain:
    scrape_interval: 5
    max_stored_deals: 250
  amazon:
    scrape_interval: 30
    max_stored_deals: 250
    urls:
      - "https://au.camelcamelcamel.com/top_drops/feed?t=daily&"
      - "https://au.camelcamelcamel.com/top_drops/feed?t=weekly&"
    # Set target price drop percentage. Only deals that meet target sent to user
    target_price_drop: 20

# notifications for android tv
pipup:
  enabled: false
  username: username # Deals of this username will be sent to android tv
  base_url: http://192.168.1.10:7979/notify # pipup url
  duration: 10
  media_type: video # possible options are video, image and web
  media_uri: https://media4.giphy.com/media/hKA6krgH9ywRa/giphy.mp4
  image_width: 200
  position: 2
  title_color: "#ffffff"
  title_size: 14
  message_color: "#ffffff"
  message_size: 12
  background_color: "#000000"
