FROM mongo:4.4.18

EXPOSE 27017


# Deploy with
# sudo docker build -t mongodb .
# sudo docker network create mongo-network
# sudo docker run -d --network mongo-network --name kramer-mongo -p 27017:27017 -v mongo-data:/data/db mongo:4.4.18
