services:
  kramerbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kramerbot
    restart: unless-stopped
    ports:
      - "5173:5173"  # Map webapp port to host
    volumes:
      - ./data:/kramerbot/data
      - ./webapp:/kramerbot/webapp
    env_file:
      - kramerbot.env
