services:
  kramerbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kramerbot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - kramerbot.env
