version: '3.7'
services:
  kramer-mongo:
    image: mongo:4.4.18
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network
    ports:
      - 27017:27017
    container_name: kramer-mongo

  kramerbot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: token.env
    networks:
      - mongo-network
    ports:
      - 3179:3179
    depends_on:
      - kramer-mongo
    container_name: kramerbot

networks:
  mongo-network:
    name: mongo-network
    driver: bridge

volumes:
  mongo-data:
    name: mongo-data
