services:
  kramer-mongo:
    image: mongo:4.4.18
    container_name: kramer-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    command: mongod --nojournal --wiredTigerCacheSizeGB 0.5
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s

  kramerbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kramerbot
    restart: unless-stopped
    depends_on:
      - kramer-mongo
    env_file:
      - kramerbot.env
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017
      - MONGO_DBNAME=usersdb
      - MONGO_COLLNAME=users
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongo-data:
    name: mongo-data
