services:
  kramer-mongo:
    image: mongo:4.4.18
    container_name: kramer-mongo
    restart: unless-stopped
    networks:
      - mongo-network
    volumes:
      - mongo-data:/data/db
    command: mongod --nojournal --wiredTigerCacheSizeGB 0.5
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s

  kramerbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kramerbot
    restart: unless-stopped
    networks:
      - mongo-network
    depends_on:
      kramer-mongo:
        condition: service_healthy
    env_file:
      - kramerbot.env
    environment:
      - MONGODB_URI=mongodb://kramer-mongo:27017

networks:
  mongo-network:
    name: mongo-network
    driver: bridge

volumes:
  mongo-data:
    name: mongo-data
