services:
  kramer-mongo:
    image: mongo:4.4.18
    container_name: kramer-mongo
    restart: unless-stopped
    networks:
      - mongo-network
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kramerbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kramerbot
    restart: unless-stopped
    networks:
      - mongo-network
    depends_on:
      kramer-mongo:
        condition: service_healthy
    env_file:
      - kramerbot.env

networks:
  mongo-network:
    name: mongo-network
    driver: bridge

volumes:
  mongo-data:
    name: mongo-data
