package util

import "math/rand"

// List of kramerisms
var kramerisms = []string{
	"Well, you’re just as pretty as any of them. You just need a nose job.",
	"Who's gonna turn down a Junior Mint? It's chocolate, it's peppermint, it's delicious.",
	"I’m out there, Jerry. And I’m loving every minute of it!",
	"I love the name ‘Isosceles.’ If I had a kid, I would name him Isosceles. Isosceles Kramer.",
	"Whadda you think junior? These hands have been soaking in ivory liquid?",
	"Now what does the little man inside you say? See you gotta listen to the little man.",
	"You contribute nothing to society!",
	"Marriage? Family? They're prisons...Man-made prisons. You're doing time...",
	"You know what would make a great coffee table book? A coffee table book about coffee tables! Get it?",
	"Because I'm like ice, buddy. When I don't like you, you've got problems.",
	"Oh, Jerry, wake up to reality. It's military thing. They're probably creating a whole army of pig warriors.",
	"Hey, Silvio, look at Jerry here, prancing around in his coat with his purse. Yup, he's a dandy. He's a real fancy boy.",
	"Jerry, all these big companies, they write off everything.",
	"You know, you really shouldn't brush 24 hours before seeing the dentist.",
	"Oh, no, you got to eat before surgery. You need your strength.",
	"Jerry, are you blind? He's a writer. He said his name was Sal Bass. Bass. Instead of salmon, he went with bass. He just substituted one fish for another.",
	"You ever dream in 3-D? It’s like the bogeyman is coming RIGHT AT YOU.",
	"Somewhere in this hospital, the anguished squeal of Pigman cries out!",
	"Well, you know what they say, you don't sell the steak, you sell the sizzle.",
	"You know I got a great idea for a cologne. The Beach. You spray it on and you smell like you just came home from the beach.",
	"Moles—freckles' ugly cousin.",
	"We have to do it. It's part of our lifestyle. It's like, uh…shaving.",
	"Because I'm like ice, buddy. When I don't like you, you've got problems.",
	"If you’re not gonna be a part of a civil society, then just get in your car and drive on over to the East Side.",
	"Hey, Silvio, look at Jerry here, prancing around in his coat with his purse. Yup, he's a dandy. He's a real fancy boy.",
	"Jerry. It's L.A. Nobody leaves. She's a seductress, she's a siren, she's a virgin, she's a whore.",
	"Jerry, my face is my livelihood, my allure...my twinkle! Everything I have I owe to this face.",
	"Yeah, because you're perfect. You're a calculating, coldhearted businesswoman. And when there's dirty work to be done, you don't mind stomping on a few throats.",
	"Now what does the little man inside you say? See you gotta listen to the little man.",
	"Who's gonna turn down a Junior Mint? It's chocolate, it's peppermint—it's delicious.",
	"I love the name ‘Isosceles.’ If I had a kid, I would name him Isosceles. Isosceles Kramer.",
	"I got news for you: Handicapped people, they don't even want to park there! They wanna be treated just like anybody else! That's why those spaces are always empty.",
	"Boxers! How do you wear these things!! Look at that—they're baggin' up, they're rising in! And there's nothing holding me in place! I'm flippin'! I'm floppin'!",
	"Oh, understudies are a very shifty bunch. The substitute teachers of the theater world.",
	"You know how there's some people you worry about whether you're going to hurt their feelings? With her, I'm looking forward to it. I'd like to get it on video, watch it in slow motion and freeze-frame it. Oh ho, yeah.",
	"That's it, George. Come on, come on. Give it to me. Come on, work it. Work it. Yeah be a man, be a man.",
	"Well, I thought they wore gloves and helmets, you know, like ‘American Gladiators.’",
	"They don't have a decent piece of fruit at the supermarket. The apples are mealy, the oranges are dry. I don't know what's going on with the papayas!",
	"I was living in twilight, George. Living in the shadows. Living in the darkness...like you.",
	"You know what would make a great coffee table book? A coffee table book about coffee tables! Get it?",
	"A bra is for ladies. I'm talking about a support undergarment specifically designed for men.",
	"There's nothing more pathetic than a grown man who’s afraid of a woman",
	"It's all a bunch of cheapskates in there anyway. People sitting around reading the newspaper attached to huge wooden sticks. Trying to save a quarter, ooh.",
	"It's a, a puffy shirt. Well, yeah, it—it's all puffy. Like the pirates used to wear.",
	"Oh, Jerry, wake up to reality. It's military thing. They're probably creating a whole army of pig warriors.",
	"You don't eat Oreos? The way you break them open? You're practically having sex with them.",
	"A gymnast, Jerry. Think of the flexibility. Mmm, that sex'll melt your face.",
	"Of course there's the possibility that you've gone right out of your mind.",
	"Hey, I'm on first and first. How can the same street intersect with itself? I must be at the nexus of the universe.",
	"She dumped me! She rolled right over me! Said I was a hipster doofus. Am I a hipster doofus?",
	"Yeah, Jerry, I’m telling you I have this power. And I have no control over it.",
	"Jerry, this is the way society functions. Aren't you a part of society? Because if you don't want to be a part of society, Jerry, why don't you just get in your car and move to the East Side?",
	"It's the timeless art of seduction. You got to join in the dance. She sends you an enticing photo, you send her one right back.",
}

// Function to randomly select a kramerism
func GetKramerism() string {
	return kramerisms[rand.Intn(len(kramerisms))]
}
